### ISSUE TITLE
v2.0 - add save button/close without saving into full screen mode

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/FASTyle#4]
v2.0 - add save button/close without saving into full screen mode

Now you have to exit the fullscreen to save your changes...

**Comment by Shade-** [comment]
Yep, but you can also use CTRL/CMD+S. I never use the button actually. I might think adding a separate button.

**Comment by Eldenroot** [comment]
Yes, you are right. I would like to see a button "Save" in a fullscreenmode if it is possible. Btw the new editor looks really nice!

**Comment by Shade-** [comment]
Fixed in 1b92515627b66b632620bd91e700710c84f8b1c0
