### ISSUE TITLE
Stylesheet -> Global.css -> diff is not working properly

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/FASTyle#5]
![image](https://user-images.githubusercontent.com/778890/31315875-b008cac0-ac21-11e7-947c-a42175a51331.png)

It shows that he content is changes but it is not...

**Comment by Shade-** [comment]
I have encountered this in the past and it might be an issue of CodeMirror. Will investigate though.

**Comment by Eldenroot** [comment]
Works fine now with your latest (unofficial) version :)
