### ISSUE TITLE
Error 500 when i try to click on fastyle

### ISSUE THREAD

**Issue by krunalcodes** [Shade-/FASTyle#6]
Installed Plugin with PHP and Template Conditionals (2.1) and PluginLibrary (13). 

When i click on FASTyle from template tab it gives me 500 error

Site is currently unable to handle this request.
HTTP ERROR 500

- PHP Fatal error:  Can't use method return value in write context fastyle.php on line 448
- Using on Sentora

**Comment by krunalcodes** [comment]
Ok this has to do with my php version. I solved it by replacing
`if (empty($mybb->get_input('title')))`

with 

`if (!$mybb->get_input('title'))`

**Comment by Shade-** [comment]
Which PHP version are you using? Either a very old one or a new one I suppose.
