### ISSUE TITLE
Left part is not scrollable

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/FASTyle#7]
With the latest Google Chrome update the left part is bugged and is not scrollable so you cann navigate through templates.

**Comment by Eldenroot** [comment]
Now I have these scroll bars
![image](https://user-images.githubusercontent.com/778890/47619760-72e6ea00-dae2-11e8-8fe3-3eace66a8d53.png)

**Comment by Shade-** [comment]
Try now please.

**Comment by Eldenroot** [comment]
I think it is still same, cannot scroll and the bars are still there :( I tried Ctrl+F5 but same, will try again in 2 hours when will be back at home

**Comment by Shade-** [comment]
I tested the last commit myself, and it works on a Mac. However, given I don't have a PC, testing there might be worthy to check for extra unneeded scrollbars. @Eldenroot

**Comment by Eldenroot** [comment]
I will test tommorow after work, I am not at home today - bussiness trip :(

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/47957746-273db000-dfbc-11e8-9911-a1814797859d.png)
So now it seems to be working! Great! I am just curious - these scrollbars had different design before, right? I am glad that it is working, thank you!

**Comment by WildcardSearch** [comment]
I'm having the same issue @Shade-

**Comment by Shade-** [comment]
See the latest commit @WildcardSearch :) It's a fix for this issue

**Comment by Shade-** [comment]
As for the scrollbars, yes, they were different. Unfortunately this is a temporary fix until I have more time to work on Simple Scrollbar and see why it's failing to work.
