### ISSUE TITLE
v2.1 issue - scroll bars

### ISSUE THREAD

**Issue by Eldenroot** [Shade-/FASTyle#8]
![image](https://user-images.githubusercontent.com/778890/54865242-c47a6480-4d62-11e9-8a22-627690f37098.png)

cache was purged

**Comment by JasminDreasond** [comment]
I sent a suggestion to fix the problem on the Pull Request 😄 
https://github.com/Shade-/FASTyle/pull/9

**Comment by Shade-** [comment]
This should be fixed in the latest commit. Let me know.
